version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://quantvault_user:quantvault_pass@db:5432/quantvault?schema=public
      - REDIS_URL=redis://cache:6379
      - JWT_SECRET=super_secret_docker_jwt_key
      - CLIENT_URL=http://localhost:3002
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    command: >
      sh -c "npx prisma db push && npm start"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: quantvault_user
      POSTGRES_PASSWORD: quantvault_pass
      POSTGRES_DB: quantvault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantvault_user -d quantvault"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
