blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/David-Antony/QuantVault-Real-Time-Investment-Portfolio-Intelligence-Platform/discussions
    about: Ask and answer questions here.
